import { useEffect, useState } from 'react';
import { Mail, Phone, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Enquiry = { id: string; parent_name: string; child_name: string | null; email: string; phone: string | null; stage: string | null; start_term: string | null; message: string | null; status: string; created_at: string };
export default function EnquiriesManager() {
  const [items, setItems] = useState<Enquiry[]>([]);
  const [error, setError] = useState('');
  const load = () => supabase.from('admissions_enquiries').select('*').order('created_at', { ascending: false }).then(({ data, error: loadError }) => { if (loadError) setError(loadError.message); else setItems((data ?? []) as Enquiry[]); });
  useEffect(() => { load(); }, []);
  const changeStatus = async (id: string, status: string) => { const { error: updateError } = await supabase.from('admissions_enquiries').update({ status }).eq('id', id); if (updateError) setError(updateError.message); else load(); };
  const remove = async (id: string) => { if (!confirm('Delete this enquiry permanently? This cannot be undone.')) return; const { error: deleteError } = await supabase.from('admissions_enquiries').delete().eq('id', id); if (deleteError) setError(deleteError.message); else load(); };
  return <section><p className="eyebrow">Admissions enquiries</p><h1 className="mt-2 font-serif text-3xl font-semibold text-navy-900">Parent enquiries</h1><p className="mt-3 text-navy-600">New enquiries submitted from the public admissions form.</p>{error && <p className="mt-5 rounded-sm border border-red-300 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-8 space-y-4">{items.map((item) => <article key={item.id} className="rounded-sm border border-navy-100 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-serif text-2xl font-semibold text-navy-900">{item.parent_name}</h2><span className="rounded-sm bg-gold-100 px-2 py-1 text-xs font-semibold text-gold-700">{item.status}</span></div><p className="mt-1 text-sm text-navy-600">Child: {item.child_name || 'Not provided'} · {item.stage || 'Stage not specified'} · {item.start_term || 'Term not specified'}</p></div><div className="flex h-fit items-center gap-3"><select value={item.status} onChange={(e) => changeStatus(item.id, e.target.value)} className="rounded-sm border border-navy-200 px-3 py-2 text-sm text-navy-700"><option>New</option><option>Contacted</option><option>Visit Booked</option><option>Closed</option></select><button type="button" onClick={() => remove(item.id)} className="inline-flex items-center gap-1 rounded-sm border border-red-200 px-3 py-2 text-sm font-medium text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4" /> Delete</button></div></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-navy-700"><a href={`mailto:${item.email}`} className="inline-flex items-center gap-2 text-gold-700"><Mail className="h-4 w-4" />{item.email}</a>{item.phone && <a href={`tel:${item.phone}`} className="inline-flex items-center gap-2"><Phone className="h-4 w-4" />{item.phone}</a>}</div>{item.message && <p className="mt-4 border-t border-navy-100 pt-4 text-sm leading-relaxed text-navy-600">{item.message}</p>}</article>)}{items.length === 0 && <div className="rounded-sm border border-dashed border-navy-200 bg-white p-12 text-center text-navy-500">No admissions enquiries yet.</div>}</div></section>;
}
