import { useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { isSupabaseConfigured, supabase } from '@/lib/supabase';
import SecondaryPagesManager from './SecondaryPagesManager';

type HomeContent = { hero_line_one: string; hero_line_two: string; hero_intro: string; hero_image: string; welcome_title: string; welcome_intro: string; welcome_image: string; visit_title: string; visit_intro: string };
const defaults: HomeContent = { hero_line_one: 'Inspiring Excellence.', hero_line_two: 'Building Tomorrow.', hero_intro: 'At Lea Valley School, we nurture confident, curious and capable learners through an education that challenges the mind, inspires creativity and develops character.', hero_image: '/school-hero.png', welcome_title: 'A Place to Learn, Grow & Thrive', welcome_intro: 'Lea Valley School educates children in the peaceful and verdant surroundings of Kay Farms Estate — a safe, welcoming and conducive environment for learning.', welcome_image: 'https://images.pexels.com/photos/8617938/pexels-photo-8617938.jpeg?auto=compress&cs=tinysrgb&w=1200', visit_title: 'Book a School Visit', visit_intro: 'Meet our team, explore our learning spaces and experience the warm community your child could become part of.' };

export default function PagesManager() {
  const [content, setContent] = useState<HomeContent>(defaults);
  const [status, setStatus] = useState('');
  useEffect(() => { supabase.from('site_content').select('content').eq('section', 'homepage').maybeSingle().then(({ data }) => { if (data?.content) setContent({ ...defaults, ...(data.content as Partial<HomeContent>) }); }); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setStatus('Saving…'); const { error } = await supabase.from('site_content').upsert({ section: 'homepage', content, updated_at: new Date().toISOString() }, { onConflict: 'section' }); setStatus(error ? error.message : 'Saved. Refresh the public homepage to see your changes.'); };
  const upload = async (file: File, field: 'hero_image' | 'welcome_image') => { setStatus('Uploading image…'); const path = `homepage/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const { error } = await supabase.storage.from('site_media').upload(path, file); if (error) { setStatus(error.message); return; } const { data } = supabase.storage.from('site_media').getPublicUrl(path); setContent({ ...content, [field]: data.publicUrl }); setStatus('Image uploaded. Save homepage text to publish it.'); };
  if (!isSupabaseConfigured) return <p className="rounded-sm border border-gold-300 bg-gold-50 p-4 text-sm text-navy-700">Connect Supabase to manage live page text.</p>;
  return <><section className="max-w-3xl"><p className="eyebrow">Pages & Text</p><h1 className="mt-2 font-serif text-3xl font-semibold text-navy-900">Homepage content</h1><p className="mt-3 text-navy-600">Update the most important public-facing messages and photographs without touching code.</p><form onSubmit={save} className="mt-8 space-y-6 rounded-sm border border-navy-100 bg-white p-6 shadow-sm"><Group label="Hero section"><ImageField label="Hero photograph" src={content.hero_image} onUpload={(file) => upload(file, 'hero_image')} /><Field label="Headline line one" value={content.hero_line_one} onChange={(value) => setContent({ ...content, hero_line_one: value })} /><Field label="Headline line two" value={content.hero_line_two} onChange={(value) => setContent({ ...content, hero_line_two: value })} /><Area label="Hero introduction" value={content.hero_intro} onChange={(value) => setContent({ ...content, hero_intro: value })} /></Group><Group label="Welcome section"><ImageField label="Welcome photograph" src={content.welcome_image} onUpload={(file) => upload(file, 'welcome_image')} /><Field label="Heading" value={content.welcome_title} onChange={(value) => setContent({ ...content, welcome_title: value })} /><Area label="Opening paragraph" value={content.welcome_intro} onChange={(value) => setContent({ ...content, welcome_intro: value })} /></Group><Group label="School visit call-to-action"><Field label="Heading" value={content.visit_title} onChange={(value) => setContent({ ...content, visit_title: value })} /><Area label="Description" value={content.visit_intro} onChange={(value) => setContent({ ...content, visit_intro: value })} /></Group><div className="flex items-center justify-between border-t border-navy-100 pt-5"><p className="text-sm text-navy-500">{status}</p><button className="inline-flex items-center gap-2 rounded-sm bg-navy-900 px-5 py-3 font-semibold text-white"><Save className="h-4 w-4" /> Save homepage changes</button></div></form></section><SecondaryPagesManager /></>;
}
function Group({ label, children }: { label: string; children: React.ReactNode }) { return <fieldset className="space-y-4 border-b border-navy-100 pb-6 last:border-0"><legend className="mb-4 text-sm font-semibold uppercase tracking-wider text-gold-700">{label}</legend>{children}</fieldset>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-navy-800">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full rounded-sm border border-navy-200 px-4 py-3 font-normal" /></label>; }
function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-navy-800">{label}<textarea rows={3} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full rounded-sm border border-navy-200 px-4 py-3 font-normal" /></label>; }
function ImageField({ label, src, onUpload }: { label: string; src: string; onUpload: (file: File) => void }) { return <div><p className="text-sm font-medium text-navy-800">{label}</p>{src && <img src={src} alt="Current selection" className="mt-2 aspect-[16/7] w-full rounded-sm object-cover" />}<input type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (file) onUpload(file); }} className="mt-3 block w-full text-sm" /></div>; }
