import { useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Settings = { phone: string; email: string; address: string; facebook: string; instagram: string; tiktok: string };
const defaults: Settings = { phone: '', email: '', address: 'Kay Farms Estate, Obawole, Iju, Lagos, Nigeria', facebook: '', instagram: '', tiktok: '' };
export default function SettingsManager() {
  const [settings, setSettings] = useState<Settings>(defaults); const [status, setStatus] = useState('');
  useEffect(() => { supabase.from('site_content').select('content').eq('section', 'site_settings').maybeSingle().then(({ data }) => { if (data?.content) setSettings({ ...defaults, ...(data.content as Partial<Settings>) }); }); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setStatus('Saving…'); const { error } = await supabase.from('site_content').upsert({ section: 'site_settings', content: settings, updated_at: new Date().toISOString() }, { onConflict: 'section' }); setStatus(error ? error.message : 'Saved. Refresh the public site to see changes.'); };
  return <section className="max-w-3xl"><p className="eyebrow">Site settings</p><h1 className="mt-2 font-serif text-3xl font-semibold text-navy-900">School details</h1><p className="mt-3 text-navy-600">Keep the contact information and social links shown across the website up to date.</p><form onSubmit={save} className="mt-8 space-y-6 rounded-sm border border-navy-100 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><Field label="School phone number" value={settings.phone} onChange={(phone) => setSettings({ ...settings, phone })} /><Field label="School email address" value={settings.email} onChange={(email) => setSettings({ ...settings, email })} /></div><Field label="Full school address" value={settings.address} onChange={(address) => setSettings({ ...settings, address })} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Facebook URL (optional)" value={settings.facebook} onChange={(facebook) => setSettings({ ...settings, facebook })} /><Field label="Instagram URL (optional)" value={settings.instagram} onChange={(instagram) => setSettings({ ...settings, instagram })} /><Field label="TikTok URL (optional)" value={settings.tiktok} onChange={(tiktok) => setSettings({ ...settings, tiktok })} /></div><div className="flex items-center justify-between border-t border-navy-100 pt-5"><p className="text-sm text-navy-500">{status}</p><button className="inline-flex items-center gap-2 rounded-sm bg-navy-900 px-5 py-3 font-semibold text-white"><Save className="h-4 w-4" /> Save settings</button></div></form></section>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-navy-800">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full rounded-sm border border-navy-200 px-4 py-3 font-normal" /></label>; }
